### ISSUE TITLE
Startup crash with mcp SDK 2.0.0: AttributeError: 'Server' object has no attribute 'list_tools'

### ISSUE THREAD

**Issue by mnishig** [tumf/mcp-shell-server#47]
## Summary

Running the published version via `uvx` fails at import time. Because
`pyproject.toml` declares `mcp>=1.1.2` with no upper bound, a fresh install
resolves to mcp 2.0.0, and the server exits before it can serve any request.

## Steps to reproduce

    uvx --refresh mcp-shell-server

## Actual result

```
Traceback (most recent call last):
File ".../bin/mcp-shell-server", line 6, in <module>
from mcp_shell_server import main
File ".../site-packages/mcp_shell_server/init.py", line 3, in <module>
from . import server
File ".../site-packages/mcp_shell_server/server.py", line 201, in <module>
@app.list_tools()
^^^^^^^^^^^^^^
AttributeError: 'Server' object has no attribute 'list_tools'
```
In Claude Desktop this
 surfaces as `Server transport closed unexpectedly`
followed by `Server disconnected`, with the traceback above in
`mcp-server-shell.log`.

## Expected result

The server starts and stays connected.

## Environment

- mcp-shell-server 1.1.3 (current latest on PyPI)
- mcp 2.0.0 (current latest on PyPI)
- uv 0.9.5
- Reproduced on Python 3.12 and 3.14
- Linux Mint 22.3
- Client: Claude Desktop

## Workaround

Pin the SDK below 2.0. In `claude_desktop_config.json`:

```json
{
  "mcpServers": {
    "shell": {
      "command": "uvx",
      "args": [
        "--with", "mcp<2",
        "mcp-shell-server"
      ],
      "env": {
        "ALLOW_COMMANDS": "ls,cat,pwd,grep,wc,touch,find"
      }
    }
  }
}
```

Note that `--with` must come before the package name, otherwise `uvx`
passes it to `mcp-shell-server` as an argument and the pin has no effect.

Equivalent one-liner for testing outside the client:

    ALLOW_COMMANDS="ls,cat,echo" uvx --with 'mcp<2' mcp-shell-server

Verified working on both Python 3.12 and the default interpreter.
